# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36bd20dde1d431c2a8ff29a71094abf2f016503ad5f11a385412f19f78eb7e5a50dc74a1d665de27731fe6a9ccd68bad65a7d5d83369fb65d442a06dc5f5a11

test:
  secret_key_base: 17cf89a89090bc77005e6ac261e877c292bc88ae8b450d817cfe811d76ff9238f34d275f60536a4eb0568c6dcc567b0e888fbdaefc4a95b6b60ef429389297f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
